### ISSUE TITLE
[High-Fi] Menu

### ISSUE THREAD

**Issue by gabrielsaruhashi** [Ameelio/pathways-client#17]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/12942772/108748405-54138980-751d-11eb-822c-84d5f7060018.png)

- [ ] Add user header to menu with pic + name
- [ ] Add logo
- [ ] Add home tab
- [ ] Add calls tab
- [ ] Add settings tab

**Out of Scope**
Contacts tab

**Additional context**

**Comment by gabrielsaruhashi** [comment]
@lspdrz 
Have you worked on this one already?

**Comment by lspdrz** [comment]
@gabrielsaruhashi Yep, through the othet tickets! I'll move to done
