### ISSUE TITLE
[Call] Video from mobile client isn't vertical

### ISSUE THREAD

**Issue by mpekala23** [Ameelio/pathways-client#8]
**Describe the bug**
Video from outside world client is shown as horizontal even though the source is vertical (as should the preview be)

**To Reproduce**
1. Join call from outside mobile client and pathways

**Expected behavior**
Vertical image

**Screenshots**
![Horizontal thingy](https://user-images.githubusercontent.com/54997453/107589712-990df680-6bd4-11eb-9de4-3412d66150ca.PNG)

**Comment by gabrielsaruhashi** [comment]
@mpekala23 does this happen every time?

I never came across this issue while video calling you

**Comment by gabrielsaruhashi** [comment]
@mpekala23 i cant repro this one so I'll close it
